name: Java CI with Maven and Allure Reports

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Allure Command Line
        run: |
          wget -O allure-2.29.0.zip https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.29.0/allure-commandline-2.29.0.zip
          unzip allure-2.29.0.zip -d /opt/allure
          export PATH="/opt/allure/allure-2.29.0/bin:$PATH"
          allure --version  # Verify Allure installation

      - name: Build and Test with Maven
        run: |
          mvn clean test

      - name: Make HTMLReport.bat Executable
        run: |
          chmod +x HTMLReport.bat

      - name: Generate Allure Reports
        run: |
          ./HTMLReport.bat  # This command starts the Allure server locally

      # Optional: You can archive the generated Allure reports as artifacts if needed
      - name: Archive Reports
        uses: actions/upload-artifact@v4
        with:
          name: allure-reports
          path: allure-reports/